# roles/common/tasks/main.yml
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  apt:
    name:
      - git
      - curl
      - unzip
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - php-xml
    state: present
